[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
memmap2 = "0.7.1"
ph = "0.7.3"
rkyv = "0.7.42"
zerocopy = "0.6.1"
